### PR TITLE
"Small" fixes

### PR DESCRIPTION
**Pull request by unLomTrois**
# So, small fixes...

## comment fire_female_headgear - because of thousands errors per second
image

## Remember: culture = northern_air_nomad; religion = air_spirituality; Someone swapped them accidentally before.
There's no such a culture like "yuan"

## changed "Male" to "Female" comments before female-gfx blocks

### CODE REVIEW

**Comment by TypicalCrusader** [comment]
remove those � from pictures = gain normal events was caused by fucked up conversion in files

**Comment by unLomTrois** [comment]
I understand, but it caused standard pictures instead normal
So, I fixed it

**Comment by TypicalCrusader** [comment]
also dont toucha my Ek generic dynasties mate, yuan culture exist in my files, this file is just so you can add new dynasties without making duplicate id

**Comment by unLomTrois** [comment]
Ok

**Pull request merged**
